# Generated by Django 6.1 on 2026-08-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_lecture_audio_file_lecture_status_lecture_transcript_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
    ]
