# Generated by Django 6.1 on 2026-08-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_remove_lecture_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='lectures.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_label', models.CharField(max_length=255)),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_segments', to='lectures.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='lectures.lecture')),
            ],
        ),
    ]
